services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pokemon
      POSTGRES_DB: paintings
    ports:
      - 127.0.0.1:5433:5432
  
  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    environment: 
      PGADMIN_DEFAULT_EMAIL: admin@domain.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  pgadmin-data: