SELECT
    -- dim_concept_skey is autogenerated
    work.id as work_id,
    work.name as name,
    work.style as style,
    CASE WHEN work_subject.subject IS NULL THEN 'Not Provided' 
         ELSE work_subject.subject 
    END as subject
FROM work
LEFT JOIN work_subject ON work.id = work_subject.work_id