SELECT
    -- dim_concept_skey is autogenerated
    work.id as work_id,
    work.name as name,
    work.style as style,
    work_subject.subject as subject
FROM work
JOIN work_subject ON work.id = work_subject.work_id